"""add auditoria_usuario table

Revision ID: 0d613912e2d2
Revises: b98779a4c853
Create Date: 2025-11-17 07:19:09.949296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d613912e2d2'
down_revision: Union[str, None] = 'b98779a4c853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_usuario_accion'), 'auditoria_usuario', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_usuario_entidad'), 'auditoria_usuario', ['entidad'], unique=False)
    op.create_index(op.f('ix_auditoria_usuario_entidad_id'), 'auditoria_usuario', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_auditoria_usuario_fecha'), 'auditoria_usuario', ['fecha'], unique=False)
    op.create_index(op.f('ix_auditoria_usuario_id'), 'auditoria_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_auditoria_usuario_usuario_id'), 'auditoria_usuario', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditoria_usuario_usuario_id'), table_name='auditoria_usuario')
    op.drop_index(op.f('ix_auditoria_usuario_id'), table_name='auditoria_usuario')
    op.drop_index(op.f('ix_auditoria_usuario_fecha'), table_name='auditoria_usuario')
    op.drop_index(op.f('ix_auditoria_usuario_entidad_id'), table_name='auditoria_usuario')
    op.drop_index(op.f('ix_auditoria_usuario_entidad'), table_name='auditoria_usuario')
    op.drop_index(op.f('ix_auditoria_usuario_accion'), table_name='auditoria_usuario')
    op.drop_table('auditoria_usuario')
    # ### end Alembic commands ###
