"""add  usuario_sucursal caja_turno caja_movimiento

Revision ID: 3d551bd697af
Revises: f5f660da501f
Create Date: 2025-12-04 19:48:15.386471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d551bd697af'
down_revision: Union[str, None] = 'f5f660da501f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caja_turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('monto_apertura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_teorico_cierre', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_real_cierre', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caja_turno_estado'), 'caja_turno', ['estado'], unique=False)
    op.create_index(op.f('ix_caja_turno_id'), 'caja_turno', ['id'], unique=False)
    op.create_index(op.f('ix_caja_turno_usuario_id'), 'caja_turno', ['usuario_id'], unique=False)
    op.create_table('usuario_sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('puede_vender', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'sucursal_id', name='uq_usuario_sucursal_unica')
    )
    op.create_index(op.f('ix_usuario_sucursal_id'), 'usuario_sucursal', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_sucursal_sucursal_id'), 'usuario_sucursal', ['sucursal_id'], unique=False)
    op.create_index(op.f('ix_usuario_sucursal_usuario_id'), 'usuario_sucursal', ['usuario_id'], unique=False)
    op.create_table('caja_movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caja_turno_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('pago_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caja_turno_id'], ['caja_turno.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caja_movimiento_caja_turno_id'), 'caja_movimiento', ['caja_turno_id'], unique=False)
    op.create_index(op.f('ix_caja_movimiento_id'), 'caja_movimiento', ['id'], unique=False)
    op.create_index(op.f('ix_caja_movimiento_pago_id'), 'caja_movimiento', ['pago_id'], unique=False)
    op.create_index(op.f('ix_caja_movimiento_pedido_id'), 'caja_movimiento', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_caja_movimiento_sucursal_id'), 'caja_movimiento', ['sucursal_id'], unique=False)
    op.create_index(op.f('ix_caja_movimiento_tipo'), 'caja_movimiento', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caja_movimiento_tipo'), table_name='caja_movimiento')
    op.drop_index(op.f('ix_caja_movimiento_sucursal_id'), table_name='caja_movimiento')
    op.drop_index(op.f('ix_caja_movimiento_pedido_id'), table_name='caja_movimiento')
    op.drop_index(op.f('ix_caja_movimiento_pago_id'), table_name='caja_movimiento')
    op.drop_index(op.f('ix_caja_movimiento_id'), table_name='caja_movimiento')
    op.drop_index(op.f('ix_caja_movimiento_caja_turno_id'), table_name='caja_movimiento')
    op.drop_table('caja_movimiento')
    op.drop_index(op.f('ix_usuario_sucursal_usuario_id'), table_name='usuario_sucursal')
    op.drop_index(op.f('ix_usuario_sucursal_sucursal_id'), table_name='usuario_sucursal')
    op.drop_index(op.f('ix_usuario_sucursal_id'), table_name='usuario_sucursal')
    op.drop_table('usuario_sucursal')
    op.drop_index(op.f('ix_caja_turno_usuario_id'), table_name='caja_turno')
    op.drop_index(op.f('ix_caja_turno_id'), table_name='caja_turno')
    op.drop_index(op.f('ix_caja_turno_estado'), table_name='caja_turno')
    op.drop_table('caja_turno')
    # ### end Alembic commands ###
