"""pedido y pago

Revision ID: 3e63549241d2
Revises: 27c763ee3a6d
Create Date: 2025-11-29 05:39:50.908179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e63549241d2'
down_revision: Union[str, None] = '27c763ee3a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('direccion_envio_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['direccion_envio_id'], ['direccion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_cliente_id'), 'pedido', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pedido_direccion_envio_id'), 'pedido', ['direccion_envio_id'], unique=False)
    op.create_index(op.f('ix_pedido_id'), 'pedido', ['id'], unique=False)
    op.create_index(op.f('ix_pedido_vendedor_id'), 'pedido', ['vendedor_id'], unique=False)
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('referencia', sa.String(length=50), nullable=True),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pago_id'), 'pago', ['id'], unique=False)
    op.create_index(op.f('ix_pago_pedido_id'), 'pago', ['pedido_id'], unique=False)
    op.drop_index('ix_auditoria_usuario_accion', table_name='auditoria_usuario')
    op.drop_index('ix_auditoria_usuario_entidad', table_name='auditoria_usuario')
    op.drop_index('ix_auditoria_usuario_entidad_id', table_name='auditoria_usuario')
    op.drop_index('ix_auditoria_usuario_fecha', table_name='auditoria_usuario')
    op.drop_index('ix_auditoria_usuario_id', table_name='auditoria_usuario')
    op.drop_index('ix_auditoria_usuario_usuario_id', table_name='auditoria_usuario')
    op.drop_table('auditoria_usuario')
    op.alter_column('categoria', 'principal',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('categoria', 'secundaria',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('direccion', 'pais',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('direccion', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('direccion', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_direccion_usuario_activa', table_name='direccion')
    op.drop_index('ix_direccion_usuario_predeterminada', table_name='direccion')
    op.drop_constraint('direccion_usuario_id_fkey', 'direccion', type_='foreignkey')
    op.create_foreign_key(None, 'direccion', 'usuario', ['usuario_id'], ['id'])
    op.alter_column('metodo_envio', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('ix_metodo_envio_activo', table_name='metodo_envio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_metodo_envio_activo', 'metodo_envio', ['activo'], unique=False)
    op.alter_column('metodo_envio', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'direccion', type_='foreignkey')
    op.create_foreign_key('direccion_usuario_id_fkey', 'direccion', 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_direccion_usuario_predeterminada', 'direccion', ['usuario_id', 'predeterminada'], unique=False)
    op.create_index('ix_direccion_usuario_activa', 'direccion', ['usuario_id', 'activa'], unique=False)
    op.alter_column('direccion', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('direccion', 'activa',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('direccion', 'pais',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('categoria', 'secundaria',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('categoria', 'principal',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_table('auditoria_usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entidad', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entidad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detalles', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='auditoria_usuario_usuario_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='auditoria_usuario_pkey')
    )
    op.create_index('ix_auditoria_usuario_usuario_id', 'auditoria_usuario', ['usuario_id'], unique=False)
    op.create_index('ix_auditoria_usuario_id', 'auditoria_usuario', ['id'], unique=False)
    op.create_index('ix_auditoria_usuario_fecha', 'auditoria_usuario', ['fecha'], unique=False)
    op.create_index('ix_auditoria_usuario_entidad_id', 'auditoria_usuario', ['entidad_id'], unique=False)
    op.create_index('ix_auditoria_usuario_entidad', 'auditoria_usuario', ['entidad'], unique=False)
    op.create_index('ix_auditoria_usuario_accion', 'auditoria_usuario', ['accion'], unique=False)
    op.drop_index(op.f('ix_pago_pedido_id'), table_name='pago')
    op.drop_index(op.f('ix_pago_id'), table_name='pago')
    op.drop_table('pago')
    op.drop_index(op.f('ix_pedido_vendedor_id'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_id'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_direccion_envio_id'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_cliente_id'), table_name='pedido')
    op.drop_table('pedido')
    # ### end Alembic commands ###
