"""add programa puntos tables

Revision ID: 528f31a4816d
Revises: d14b0ddfb37e
Create Date: 2025-11-27 17:53:22.476522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528f31a4816d'
down_revision: Union[str, None] = 'd14b0ddfb37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programa_puntos_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('puntos_por_colon', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('valor_colon_por_punto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_minimo_para_redimir', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('porcentaje_max_descuento', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_descuento_por_compra_colones', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programa_puntos_config_id'), 'programa_puntos_config', ['id'], unique=False)
    op.create_table('movimiento_puntos_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimiento_puntos_usuario_id'), 'movimiento_puntos_usuario', ['id'], unique=False)
    op.create_table('saldo_puntos_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_saldo_puntos_usuario_id'), 'saldo_puntos_usuario', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saldo_puntos_usuario_id'), table_name='saldo_puntos_usuario')
    op.drop_table('saldo_puntos_usuario')
    op.drop_index(op.f('ix_movimiento_puntos_usuario_id'), table_name='movimiento_puntos_usuario')
    op.drop_table('movimiento_puntos_usuario')
    op.drop_index(op.f('ix_programa_puntos_config_id'), table_name='programa_puntos_config')
    op.drop_table('programa_puntos_config')
    # ### end Alembic commands ###
