"""add provincia to sucursal and sucursal_id to pedido

Revision ID: 5d8014a33ca3
Revises: feb7c5922cf8
Create Date: 2025-11-30 03:46:41.266546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8014a33ca3'
down_revision: Union[str, None] = 'feb7c5922cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('sucursal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pedido_sucursal_id'), 'pedido', ['sucursal_id'], unique=False)
    op.create_foreign_key(None, 'pedido', 'sucursal', ['sucursal_id'], ['id'], ondelete='RESTRICT')
    op.add_column('sucursal', sa.Column('provincia', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sucursal', 'provincia')
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.drop_index(op.f('ix_pedido_sucursal_id'), table_name='pedido')
    op.drop_column('pedido', 'sucursal_id')
    # ### end Alembic commands ###
