"""add home_hero

Revision ID: 655f06a39672
Revises: 6d54b6f44192
Create Date: 2025-11-26 03:28:52.717094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655f06a39672'
down_revision: Union[str, None] = '6d54b6f44192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_hero_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('banner1_url', sa.String(length=500), nullable=True),
    sa.Column('banner2_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_hero_config_id'), 'home_hero_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_home_hero_config_id'), table_name='home_hero_config')
    op.drop_table('home_hero_config')
    # ### end Alembic commands ###
