"""add categoria principal/secundaria

Revision ID: 6d54b6f44192
Revises: abc123marca001
Create Date: 2025-11-25 22:54:09.295375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d54b6f44192'
down_revision: Union[str, None] = 'abc123marca001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_categoria',
    sa.Column('categoria_principal_id', sa.Integer(), nullable=False),
    sa.Column('categoria_secundaria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_principal_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['categoria_secundaria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('categoria_principal_id', 'categoria_secundaria_id')
    )
    op.add_column('categoria', sa.Column('principal', sa.Boolean(), nullable=True))
    op.add_column('categoria', sa.Column('secundaria', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categoria', 'secundaria')
    op.drop_column('categoria', 'principal')
    op.drop_table('categoria_categoria')
    # ### end Alembic commands ###
