"""add impuesto to pedido_item and impuesto_total to pedido

Revision ID: 8336a756901c
Revises: 9e14402cd8bf
Create Date: 2025-12-05 23:11:51.840676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8336a756901c'
down_revision: Union[str, None] = '9e14402cd8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido_item', sa.Column('impuesto', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido_item', 'impuesto')
    # ### end Alembic commands ###
