"""Agregar impuesto a venta_pos_item

Revision ID: 9e14402cd8bf
Revises: f565ee90a082
Create Date: 2025-12-05 19:37:43.601384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e14402cd8bf'
down_revision: Union[str, None] = 'f565ee90a082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venta_pos', sa.Column('impuesto', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venta_pos', 'impuesto')
    # ### end Alembic commands ###
