"""empty message

Revision ID: a324e1b56115
Revises: e121229f9216
Create Date: 2025-12-04 04:52:16.237589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a324e1b56115'
down_revision: Union[str, None] = 'e121229f9216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rmas', sa.Column('evidencia_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rmas', 'evidencia_url')
    # ### end Alembic commands ###
