"""add slug to categoria

Revision ID: a73a44bcea87
Revises: 129266c307e1
Create Date: 2025-12-01 19:03:23.878209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73a44bcea87'
down_revision: Union[str, None] = '129266c307e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoria', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_categoria_slug'), 'categoria', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categoria_slug'), table_name='categoria')
    op.drop_column('categoria', 'slug')
    # ### end Alembic commands ###
