"""add marca to variante

Revision ID: b14c8aef92da
Revises: 54aeea7b0035
Create Date: 2025-11-24 13:10:35.057948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14c8aef92da'
down_revision: Union[str, None] = '54aeea7b0035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variante', sa.Column('marca', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_variante_marca'), 'variante', ['marca'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variante_marca'), table_name='variante')
    op.drop_column('variante', 'marca')
    # ### end Alembic commands ###
