"""add carrito and carrito_item

Revision ID: d14b0ddfb37e
Revises: 78a2f97d0521
Create Date: 2025-11-26 17:59:34.404388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd14b0ddfb37e'
down_revision: Union[str, None] = '78a2f97d0521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carrito', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('carrito', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_carrito_estado', table_name='carrito')
    op.create_index(op.f('ix_carrito_id'), 'carrito', ['id'], unique=False)
    op.alter_column('carrito_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('carrito_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_carrito_item_carrito_variante', 'carrito_item', type_='unique')
    op.create_index(op.f('ix_carrito_item_id'), 'carrito_item', ['id'], unique=False)
    op.drop_constraint('carrito_item_variante_id_fkey', 'carrito_item', type_='foreignkey')
    op.create_foreign_key(None, 'carrito_item', 'variante', ['variante_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_favorito_usuario_variante', 'favorito', type_='unique')
    op.create_index(op.f('ix_favorito_id'), 'favorito', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorito_id'), table_name='favorito')
    op.create_unique_constraint('uq_favorito_usuario_variante', 'favorito', ['usuario_id', 'variante_id'])
    op.drop_constraint(None, 'carrito_item', type_='foreignkey')
    op.create_foreign_key('carrito_item_variante_id_fkey', 'carrito_item', 'variante', ['variante_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_carrito_item_id'), table_name='carrito_item')
    op.create_unique_constraint('uq_carrito_item_carrito_variante', 'carrito_item', ['carrito_id', 'variante_id'])
    op.alter_column('carrito_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('carrito_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_carrito_id'), table_name='carrito')
    op.create_index('ix_carrito_estado', 'carrito', ['estado'], unique=False)
    op.alter_column('carrito', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('carrito', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
