"""Agregar tabla pedido_item y campos a pedido

Revision ID: d3444cd9751b
Revises: add_cancelacion_pedido
Create Date: 2025-11-30 01:36:38.235112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3444cd9751b'
down_revision: Union[str, None] = 'add_cancelacion_pedido'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pedido_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pedido_id', sa.Integer(), nullable=False),
        sa.Column('variante_id', sa.Integer(), nullable=False),
        sa.Column('producto_id', sa.Integer(), nullable=False),
        sa.Column('cantidad', sa.Integer(), nullable=False),
        sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['variante_id'], ['variante.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_item_id'), 'pedido_item', ['id'], unique=False)
    op.create_index(op.f('ix_pedido_item_pedido_id'), 'pedido_item', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_pedido_item_producto_id'), 'pedido_item', ['producto_id'], unique=False)
    op.create_index(op.f('ix_pedido_item_variante_id'), 'pedido_item', ['variante_id'], unique=False)

    # ------- carrito -------
    op.alter_column(
        'carrito',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'carrito',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.execute("DROP INDEX IF EXISTS ix_carrito_estado")
    # op.create_index(op.f('ix_carrito_id'), 'carrito', ['id'], unique=False)

    # ------- carrito_item -------
    op.alter_column(
        'carrito_item',
        'precio_unitario',
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        'carrito_item',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'carrito_item',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )

    # Eliminar constraint único solo si existe
    op.execute("""
        ALTER TABLE carrito_item
        DROP CONSTRAINT IF EXISTS carrito_item_carrito_id_variante_id_key
    """)

    # Eliminar índice antiguo solo si existe y crear el nuevo
    op.execute("DROP INDEX IF EXISTS ix_carrito_item_id")
    op.create_index(op.f('ix_carrito_item_id'), 'carrito_item', ['id'], unique=False)

    # ------- favorito -------
    op.execute("""
        ALTER TABLE favorito
        DROP CONSTRAINT IF EXISTS favorito_usuario_id_variante_id_key
    """)
    op.execute("DROP INDEX IF EXISTS ix_favorito_id")
    op.create_index(op.f('ix_favorito_id'), 'favorito', ['id'], unique=False)

    # ------- movimiento_puntos_usuario -------
    op.alter_column(
        'movimiento_puntos_usuario',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )

    # Eliminar índices antiguos de forma segura
    op.execute("DROP INDEX IF EXISTS ix_movimiento_puntos_pedido_id")
    op.execute("DROP INDEX IF EXISTS ix_movimiento_puntos_tipo")
    op.execute("DROP INDEX IF EXISTS ix_movimiento_puntos_usuario_id")

    # Crear índice nuevo sobre id
    op.create_index(
        op.f('ix_movimiento_puntos_usuario_id'),
        'movimiento_puntos_usuario',
        ['id'],
        unique=False,
    )

        # Eliminar FKs antiguos de forma segura (solo si existen)
    op.execute("""
        ALTER TABLE movimiento_puntos_usuario
        DROP CONSTRAINT IF EXISTS movimiento_puntos_pedido_id_fkey
    """)
    op.execute("""
        ALTER TABLE movimiento_puntos_usuario
        DROP CONSTRAINT IF EXISTS movimiento_puntos_usuario_id_fkey
    """)

    # Crear el nuevo FK solo hacia usuario
    op.create_foreign_key(
        None,
        'movimiento_puntos_usuario',
        'usuario',
        ['usuario_id'],
        ['id'],
    )

        # Eliminar columnas que ya no se usarán (solo si existen)
    op.execute("""
        ALTER TABLE movimiento_puntos_usuario
        DROP COLUMN IF EXISTS saldo_anterior
    """)
    op.execute("""
        ALTER TABLE movimiento_puntos_usuario
        DROP COLUMN IF EXISTS pedido_id
    """)
    op.execute("""
        ALTER TABLE movimiento_puntos_usuario
        DROP COLUMN IF EXISTS saldo_nuevo
    """)



    # ------- pedido: nuevas columnas -------
    op.add_column('pedido', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pedido', sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pedido', sa.Column('descuento_puntos', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pedido', sa.Column('puntos_ganados', sa.Integer(), nullable=True))
    op.add_column('pedido', sa.Column('metodo_envio', sa.String(length=50), nullable=True))
    op.add_column('pedido', sa.Column('numero_pedido', sa.String(length=50), nullable=True))

    op.execute("""
        UPDATE pedido 
        SET 
            subtotal = total,
            costo_envio = 0,
            descuento_puntos = 0,
            puntos_ganados = 0,
            metodo_envio = 'Envío Estándar',
            numero_pedido = 'ORD-' || id || '-' || CAST(EXTRACT(epoch FROM fecha_creacion) * 1000 AS BIGINT)
        WHERE subtotal IS NULL
    """)

    op.alter_column(
        'pedido',
        'subtotal',
        existing_type=sa.Numeric(precision=10, scale=2),
        nullable=False,
    )

    op.create_index(op.f('ix_pedido_numero_pedido'), 'pedido', ['numero_pedido'], unique=True)

        # ------- programa_puntos_config -------
    op.alter_column(
        'programa_puntos_config',
        'puntos_por_colon',
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=10, scale=4),
        existing_nullable=False,
        existing_server_default=sa.text('1.00'),
    )
    op.alter_column(
        'programa_puntos_config',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'programa_puntos_config',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )

    # Evitar duplicar el índice si ya existe
    op.execute("DROP INDEX IF EXISTS ix_programa_puntos_config_id")
    op.create_index(
        op.f('ix_programa_puntos_config_id'),
        'programa_puntos_config',
        ['id'],
        unique=False,
    )


        # ------- saldo_puntos_usuario -------
    op.alter_column(
        'saldo_puntos_usuario',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )

    op.execute("DROP INDEX IF EXISTS ix_saldo_puntos_usuario_id")
    op.create_index(
        op.f('ix_saldo_puntos_usuario_id'),
        'saldo_puntos_usuario',
        ['id'],
        unique=False,
    )

    # Eliminar FK antiguo solo si existe
    op.execute("""
        ALTER TABLE saldo_puntos_usuario
        DROP CONSTRAINT IF EXISTS saldo_puntos_usuario_id_fkey
    """)

    # Crear el nuevo FK hacia usuario
    op.create_foreign_key(
        None,
        'saldo_puntos_usuario',
        'usuario',
        ['usuario_id'],
        ['id'],
    )

    # Eliminar columnas viejas solo si existen
    op.execute("""
        ALTER TABLE saldo_puntos_usuario
        DROP COLUMN IF EXISTS total_redimido
    """)
    op.execute("""
        ALTER TABLE saldo_puntos_usuario
        DROP COLUMN IF EXISTS created_at
    """)
    op.execute("""
        ALTER TABLE saldo_puntos_usuario
        DROP COLUMN IF EXISTS saldo_actual
    """)
    op.execute("""
        ALTER TABLE saldo_puntos_usuario
        DROP COLUMN IF EXISTS total_acumulado
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saldo_puntos_usuario', sa.Column('total_acumulado', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('saldo_puntos_usuario', sa.Column('saldo_actual', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('saldo_puntos_usuario', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('saldo_puntos_usuario', sa.Column('total_redimido', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'saldo_puntos_usuario', type_='foreignkey')
    op.create_foreign_key('saldo_puntos_usuario_id_fkey', 'saldo_puntos_usuario', 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_saldo_puntos_usuario_id'), table_name='saldo_puntos_usuario')
    op.create_index('ix_saldo_puntos_usuario_id', 'saldo_puntos_usuario', ['usuario_id'], unique=False)
    op.alter_column('saldo_puntos_usuario', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_programa_puntos_config_id'), table_name='programa_puntos_config')
    op.alter_column('programa_puntos_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('programa_puntos_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('programa_puntos_config', 'puntos_por_colon',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('1.00'))
    op.drop_index(op.f('ix_pedido_numero_pedido'), table_name='pedido')
    op.drop_column('pedido', 'numero_pedido')
    op.drop_column('pedido', 'metodo_envio')
    op.drop_column('pedido', 'puntos_ganados')
    op.drop_column('pedido', 'descuento_puntos')
    op.drop_column('pedido', 'costo_envio')
    op.drop_column('pedido', 'subtotal')
    op.add_column('movimiento_puntos_usuario', sa.Column('saldo_nuevo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movimiento_puntos_usuario', sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movimiento_puntos_usuario', sa.Column('saldo_anterior', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'movimiento_puntos_usuario', type_='foreignkey')
    op.create_foreign_key('movimiento_puntos_usuario_id_fkey', 'movimiento_puntos_usuario', 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('movimiento_puntos_pedido_id_fkey', 'movimiento_puntos_usuario', 'pedido', ['pedido_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_movimiento_puntos_usuario_id'), table_name='movimiento_puntos_usuario')
    op.create_index('ix_movimiento_puntos_usuario_id', 'movimiento_puntos_usuario', ['usuario_id'], unique=False)
    op.create_index('ix_movimiento_puntos_tipo', 'movimiento_puntos_usuario', ['tipo'], unique=False)
    op.create_index('ix_movimiento_puntos_pedido_id', 'movimiento_puntos_usuario', ['pedido_id'], unique=False)
    op.alter_column('movimiento_puntos_usuario', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_favorito_id'), table_name='favorito')
    op.create_unique_constraint('favorito_usuario_id_variante_id_key', 'favorito', ['usuario_id', 'variante_id'])
    op.drop_index(op.f('ix_carrito_item_id'), table_name='carrito_item')
    op.create_unique_constraint('carrito_item_carrito_id_variante_id_key', 'carrito_item', ['carrito_id', 'variante_id'])
    op.alter_column('carrito_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('carrito_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('carrito_item', 'precio_unitario',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_carrito_id'), table_name='carrito')
    op.create_index('ix_carrito_estado', 'carrito', ['estado'], unique=False)
    op.alter_column('carrito', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('carrito', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pedido_item_variante_id'), table_name='pedido_item')
    op.drop_index(op.f('ix_pedido_item_producto_id'), table_name='pedido_item')
    op.drop_index(op.f('ix_pedido_item_pedido_id'), table_name='pedido_item')
    op.drop_index(op.f('ix_pedido_item_id'), table_name='pedido_item')
    op.drop_table('pedido_item')
    # ### end Alembic commands ###