"""Agregar tabla pedido_item y campos a pedido

Revision ID: d3444cd9751b
Revises: add_cancelacion_pedido
Create Date: 2025-11-30 01:36:38.235112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3444cd9751b'
down_revision: Union[str, None] = 'add_cancelacion_pedido'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variante_id'], ['variante.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_item_id'), 'pedido_item', ['id'], unique=False)
    op.create_index(op.f('ix_pedido_item_pedido_id'), 'pedido_item', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_pedido_item_producto_id'), 'pedido_item', ['producto_id'], unique=False)
    op.create_index(op.f('ix_pedido_item_variante_id'), 'pedido_item', ['variante_id'], unique=False)
    op.alter_column('carrito', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('carrito', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_carrito_estado', table_name='carrito')
    op.create_index(op.f('ix_carrito_id'), 'carrito', ['id'], unique=False)
    op.alter_column('carrito_item', 'precio_unitario',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('carrito_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('carrito_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('carrito_item_carrito_id_variante_id_key', 'carrito_item', type_='unique')
    op.create_index(op.f('ix_carrito_item_id'), 'carrito_item', ['id'], unique=False)
    op.drop_constraint('favorito_usuario_id_variante_id_key', 'favorito', type_='unique')
    op.create_index(op.f('ix_favorito_id'), 'favorito', ['id'], unique=False)
    op.alter_column('movimiento_puntos_usuario', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_movimiento_puntos_pedido_id', table_name='movimiento_puntos_usuario')
    op.drop_index('ix_movimiento_puntos_tipo', table_name='movimiento_puntos_usuario')
    op.drop_index('ix_movimiento_puntos_usuario_id', table_name='movimiento_puntos_usuario')
    op.create_index(op.f('ix_movimiento_puntos_usuario_id'), 'movimiento_puntos_usuario', ['id'], unique=False)
    op.drop_constraint('movimiento_puntos_pedido_id_fkey', 'movimiento_puntos_usuario', type_='foreignkey')
    op.drop_constraint('movimiento_puntos_usuario_id_fkey', 'movimiento_puntos_usuario', type_='foreignkey')
    op.create_foreign_key(None, 'movimiento_puntos_usuario', 'usuario', ['usuario_id'], ['id'])
    op.drop_column('movimiento_puntos_usuario', 'saldo_anterior')
    op.drop_column('movimiento_puntos_usuario', 'pedido_id')
    op.drop_column('movimiento_puntos_usuario', 'saldo_nuevo')
    
    # 🔧 SECCIÓN CORREGIDA: Agregar columnas a pedido de forma segura
    # Primero agregamos las columnas como nullable
    op.add_column('pedido', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pedido', sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pedido', sa.Column('descuento_puntos', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pedido', sa.Column('puntos_ganados', sa.Integer(), nullable=True))
    op.add_column('pedido', sa.Column('metodo_envio', sa.String(length=50), nullable=True))
    op.add_column('pedido', sa.Column('numero_pedido', sa.String(length=50), nullable=True))
    
    # Llenar valores para pedidos existentes
    op.execute("""
        UPDATE pedido 
        SET 
            subtotal = total,
            costo_envio = 0,
            descuento_puntos = 0,
            puntos_ganados = 0,
            metodo_envio = 'Envío Estándar',
            numero_pedido = 'ORD-' || id || '-' || CAST(EXTRACT(epoch FROM fecha_creacion) * 1000 AS BIGINT)
        WHERE subtotal IS NULL
    """)
    
    # Ahora hacer subtotal NOT NULL (después de llenar los datos)
    op.alter_column('pedido', 'subtotal',
               existing_type=sa.Numeric(precision=10, scale=2),
               nullable=False)
    # 🔧 FIN DE SECCIÓN CORREGIDA
    
    op.create_index(op.f('ix_pedido_numero_pedido'), 'pedido', ['numero_pedido'], unique=True)
    op.alter_column('programa_puntos_config', 'puntos_por_colon',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text('1.00'))
    op.alter_column('programa_puntos_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('programa_puntos_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_programa_puntos_config_id'), 'programa_puntos_config', ['id'], unique=False)
    op.alter_column('saldo_puntos_usuario', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_saldo_puntos_usuario_id', table_name='saldo_puntos_usuario')
    op.create_index(op.f('ix_saldo_puntos_usuario_id'), 'saldo_puntos_usuario', ['id'], unique=False)
    op.drop_constraint('saldo_puntos_usuario_id_fkey', 'saldo_puntos_usuario', type_='foreignkey')
    op.create_foreign_key(None, 'saldo_puntos_usuario', 'usuario', ['usuario_id'], ['id'])
    op.drop_column('saldo_puntos_usuario', 'total_redimido')
    op.drop_column('saldo_puntos_usuario', 'created_at')
    op.drop_column('saldo_puntos_usuario', 'saldo_actual')
    op.drop_column('saldo_puntos_usuario', 'total_acumulado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saldo_puntos_usuario', sa.Column('total_acumulado', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('saldo_puntos_usuario', sa.Column('saldo_actual', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('saldo_puntos_usuario', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('saldo_puntos_usuario', sa.Column('total_redimido', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'saldo_puntos_usuario', type_='foreignkey')
    op.create_foreign_key('saldo_puntos_usuario_id_fkey', 'saldo_puntos_usuario', 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_saldo_puntos_usuario_id'), table_name='saldo_puntos_usuario')
    op.create_index('ix_saldo_puntos_usuario_id', 'saldo_puntos_usuario', ['usuario_id'], unique=False)
    op.alter_column('saldo_puntos_usuario', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_programa_puntos_config_id'), table_name='programa_puntos_config')
    op.alter_column('programa_puntos_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('programa_puntos_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('programa_puntos_config', 'puntos_por_colon',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('1.00'))
    op.drop_index(op.f('ix_pedido_numero_pedido'), table_name='pedido')
    op.drop_column('pedido', 'numero_pedido')
    op.drop_column('pedido', 'metodo_envio')
    op.drop_column('pedido', 'puntos_ganados')
    op.drop_column('pedido', 'descuento_puntos')
    op.drop_column('pedido', 'costo_envio')
    op.drop_column('pedido', 'subtotal')
    op.add_column('movimiento_puntos_usuario', sa.Column('saldo_nuevo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movimiento_puntos_usuario', sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movimiento_puntos_usuario', sa.Column('saldo_anterior', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'movimiento_puntos_usuario', type_='foreignkey')
    op.create_foreign_key('movimiento_puntos_usuario_id_fkey', 'movimiento_puntos_usuario', 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('movimiento_puntos_pedido_id_fkey', 'movimiento_puntos_usuario', 'pedido', ['pedido_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_movimiento_puntos_usuario_id'), table_name='movimiento_puntos_usuario')
    op.create_index('ix_movimiento_puntos_usuario_id', 'movimiento_puntos_usuario', ['usuario_id'], unique=False)
    op.create_index('ix_movimiento_puntos_tipo', 'movimiento_puntos_usuario', ['tipo'], unique=False)
    op.create_index('ix_movimiento_puntos_pedido_id', 'movimiento_puntos_usuario', ['pedido_id'], unique=False)
    op.alter_column('movimiento_puntos_usuario', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_favorito_id'), table_name='favorito')
    op.create_unique_constraint('favorito_usuario_id_variante_id_key', 'favorito', ['usuario_id', 'variante_id'])
    op.drop_index(op.f('ix_carrito_item_id'), table_name='carrito_item')
    op.create_unique_constraint('carrito_item_carrito_id_variante_id_key', 'carrito_item', ['carrito_id', 'variante_id'])
    op.alter_column('carrito_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('carrito_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('carrito_item', 'precio_unitario',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_carrito_id'), table_name='carrito')
    op.create_index('ix_carrito_estado', 'carrito', ['estado'], unique=False)
    op.alter_column('carrito', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('carrito', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pedido_item_variante_id'), table_name='pedido_item')
    op.drop_index(op.f('ix_pedido_item_producto_id'), table_name='pedido_item')
    op.drop_index(op.f('ix_pedido_item_pedido_id'), table_name='pedido_item')
    op.drop_index(op.f('ix_pedido_item_id'), table_name='pedido_item')
    op.drop_table('pedido_item')
    # ### end Alembic commands ###