"""Agregar tablas RMA

Revision ID: e121229f9216
Revises: b474f8f02beb
Create Date: 2025-12-04 03:45:37.685577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e121229f9216'
down_revision: Union[str, None] = 'b474f8f02beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('DEVOLUCION', 'CAMBIO', name='rmatipo'), nullable=False),
    sa.Column('estado', sa.Enum('SOLICITADO', 'EN_REVISION', 'APROBADO', 'RECHAZADO', 'COMPLETADO', name='rmaestado'), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('respuesta_admin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rmas_estado'), 'rmas', ['estado'], unique=False)
    op.create_index(op.f('ix_rmas_id'), 'rmas', ['id'], unique=False)
    op.create_index(op.f('ix_rmas_pedido_id'), 'rmas', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_rmas_usuario_id'), 'rmas', ['usuario_id'], unique=False)
    op.create_table('rma_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rma_id', sa.Integer(), nullable=False),
    sa.Column('pedido_item_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_item_id'], ['pedido_item.id'], ),
    sa.ForeignKeyConstraint(['rma_id'], ['rmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rma_items_id'), 'rma_items', ['id'], unique=False)
    op.create_index(op.f('ix_auditoria_usuario_id'), 'auditoria_usuario', ['id'], unique=False)
    op.alter_column('categoria', 'slug',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categoria', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_index(op.f('ix_auditoria_usuario_id'), table_name='auditoria_usuario')
    op.drop_index(op.f('ix_rma_items_id'), table_name='rma_items')
    op.drop_table('rma_items')
    op.drop_index(op.f('ix_rmas_usuario_id'), table_name='rmas')
    op.drop_index(op.f('ix_rmas_pedido_id'), table_name='rmas')
    op.drop_index(op.f('ix_rmas_id'), table_name='rmas')
    op.drop_index(op.f('ix_rmas_estado'), table_name='rmas')
    op.drop_table('rmas')
    # ### end Alembic commands ###
