"""add pago_pos

Revision ID: f565ee90a082
Revises: ff4d996f0082
Create Date: 2025-12-04 21:25:14.961639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f565ee90a082'
down_revision: Union[str, None] = 'ff4d996f0082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago_pos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_pos_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('referencia', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venta_pos_id'], ['venta_pos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pago_pos_id'), 'pago_pos', ['id'], unique=False)
    op.create_index(op.f('ix_pago_pos_venta_pos_id'), 'pago_pos', ['venta_pos_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pago_pos_venta_pos_id'), table_name='pago_pos')
    op.drop_index(op.f('ix_pago_pos_id'), table_name='pago_pos')
    op.drop_table('pago_pos')
    # ### end Alembic commands ###
