"""add pos canal usuario_sucursal caja_turno caja_movimiento

Revision ID: f5f660da501f
Revises: 65ee2f05e174
Create Date: 2025-12-04 18:39:06.221972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f660da501f'
down_revision: Union[str, None] = '65ee2f05e174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('canal', sa.String(length=20), nullable=False, server_default='ONLINE'))
    op.create_index(op.f('ix_pedido_canal'), 'pedido', ['canal'], unique=False)
    # ### end Alembic commands ###
    op.alter_column('pedido', 'canal', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_canal'), table_name='pedido')
    op.drop_column('pedido', 'canal')
    # ### end Alembic commands ###
