"""add venta_pos tables and link caja_movimiento

Revision ID: ff4d996f0082
Revises: 3d551bd697af
Create Date: 2025-12-04 20:58:35.290561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4d996f0082'
down_revision: Union[str, None] = '3d551bd697af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venta_pos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('nombre_cliente', sa.String(length=200), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento_puntos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('puntos_ganados', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cancelado', sa.Boolean(), nullable=False),
    sa.Column('motivo_cancelacion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_pos_cancelado'), 'venta_pos', ['cancelado'], unique=False)
    op.create_index(op.f('ix_venta_pos_cliente_id'), 'venta_pos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_venta_pos_estado'), 'venta_pos', ['estado'], unique=False)
    op.create_index(op.f('ix_venta_pos_id'), 'venta_pos', ['id'], unique=False)
    op.create_index(op.f('ix_venta_pos_sucursal_id'), 'venta_pos', ['sucursal_id'], unique=False)
    op.create_index(op.f('ix_venta_pos_vendedor_id'), 'venta_pos', ['vendedor_id'], unique=False)
    op.create_table('venta_pos_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_pos_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variante_id'], ['variante.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venta_pos_id'], ['venta_pos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_pos_item_id'), 'venta_pos_item', ['id'], unique=False)
    op.create_index(op.f('ix_venta_pos_item_producto_id'), 'venta_pos_item', ['producto_id'], unique=False)
    op.create_index(op.f('ix_venta_pos_item_variante_id'), 'venta_pos_item', ['variante_id'], unique=False)
    op.create_index(op.f('ix_venta_pos_item_venta_pos_id'), 'venta_pos_item', ['venta_pos_id'], unique=False)
    op.add_column('caja_movimiento', sa.Column('venta_pos_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_caja_movimiento_venta_pos_id'), 'caja_movimiento', ['venta_pos_id'], unique=False)
    op.create_foreign_key(None, 'caja_movimiento', 'venta_pos', ['venta_pos_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'caja_movimiento', type_='foreignkey')
    op.drop_index(op.f('ix_caja_movimiento_venta_pos_id'), table_name='caja_movimiento')
    op.drop_column('caja_movimiento', 'venta_pos_id')
    op.drop_index(op.f('ix_venta_pos_item_venta_pos_id'), table_name='venta_pos_item')
    op.drop_index(op.f('ix_venta_pos_item_variante_id'), table_name='venta_pos_item')
    op.drop_index(op.f('ix_venta_pos_item_producto_id'), table_name='venta_pos_item')
    op.drop_index(op.f('ix_venta_pos_item_id'), table_name='venta_pos_item')
    op.drop_table('venta_pos_item')
    op.drop_index(op.f('ix_venta_pos_vendedor_id'), table_name='venta_pos')
    op.drop_index(op.f('ix_venta_pos_sucursal_id'), table_name='venta_pos')
    op.drop_index(op.f('ix_venta_pos_id'), table_name='venta_pos')
    op.drop_index(op.f('ix_venta_pos_estado'), table_name='venta_pos')
    op.drop_index(op.f('ix_venta_pos_cliente_id'), table_name='venta_pos')
    op.drop_index(op.f('ix_venta_pos_cancelado'), table_name='venta_pos')
    op.drop_table('venta_pos')
    # ### end Alembic commands ###
